# Generated by Django 5.2.5 on 2025-08-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred_name', models.CharField(max_length=100)),
                ('sbd_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
