# Generated by Django 5.2.5 on 2025-08-29 20:15

import django.db.models.deletion
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Referencia')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('sbu', models.CharField(blank=True, max_length=100, null=True, verbose_name='SBU')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('precio_sin_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio antes de IVA')),
                ('empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=productos.models.image_upload_path)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
        ),
    ]
