# Generated by Django 5.2.5 on 2025-08-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_con_iva',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='referencia',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sbu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SBU'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='Referencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio antes de IVA'),
        ),
    ]
