name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  # formateo automático 
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install black isort flake8
      - name: Format code (black)
        run: black .
      - name: Sort imports (isort)
        run: isort .
      - name: Lint code (flake8)
        run: flake8 .

   # seguridad de código y dependencias (pip-audit, falla si hay vulns)
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      # instala bandit y pip-audit
      - run: pip install bandit pip-audit

      - name: Security analysis (Bandit)
        run: bandit -r . -x "env,**/migrations/**,**/tests/**"

      - name: Dependency security check (pip-audit)
        run: pip-audit -r requirements.txt --format table
